background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
}

general {
    hide_cursor = true
}

input-field {
    monitor =
    size = 260, 50
    outline_thickness = 2

    dots_size = 0.2
    dots_spacing = 0.35

    outer_color = rgba(cdd6f4ff)
    inner_color = rgba(1e1e2ecc)
    font_color = rgba(cdd6f4ff)

    fade_on_empty = false
    rounding = 14

    placeholder_text = Password...
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(cdd6f4ff)

    font_size = 72
    font_family = JetBrainsMono Nerd Font

    position = 0, 80
    halign = center
    valign = center
}