decoration {
    rounding = 18

    active_opacity = 1.0
    inactive_opacity = 0.94

    shadow {
        enabled = true
        range = 20
        render_power = 4
        color = rgba(00000055)
    }

    blur {
        enabled = true
        size = 8
        passes = 3

        ignore_opacity = true
        new_optimizations = true
        xray = false
    }
}


