general {
    gaps_in = 5
    gaps_out = 14

    border_size = 2

    col.active_border = rgba(cdd6f4ee)
    col.inactive_border = rgba(313244aa)

    resize_on_border = false
    allow_tearing = false

    layout = dwindle
}

