# Float utility apps
windowrule = float on, match:class ^(pavucontrol)$
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(nm-connection-editor)$

# Center floating windows
windowrule = center on, match:float true

# Picture-in-picture
windowrule = pin on, match:title ^(Picture-in-Picture)$

# Kitty opacity
windowrule = opacity 0.95 0.90, match:class ^(kitty)$

# Prevent sleep while fullscreen
windowrule = idle_inhibit fullscreen, match:fullscreen true

